version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: ../backend/
    restart: always
    volumes:
      - static_storage:/app/static_storage/
      - media_storage:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_storage:/usr/share/nginx/html/static_storage/:ro
      - media_storage:/usr/share/nginx/html/media/:ro

volumes:
  db:
  static_storage:
  media_storage:
